# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 22:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0002_auto_20160118_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
